[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
mpl_core_appdata_example = "BicWwtfJJAzWfAp2hzpdnyvvjB5TKnikAXxLVZbHcM2U"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
